version: "3.8"

services:
  mongo:
    image: mongo:7.0
    container_name: vaa-mongo-db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "mongo_data:/data/db"
      - "mongo_config:/data/configdb"
    networks:
      - VAA

  mongo-express:
    image: mongo-express:latest
    container_name: vaa-mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: true
    ports:
      - 8081:8081
    networks:
      - VAA
    depends_on:
      - mongo
  rabbitmq:
    image: 'rabbitmq:3.13.1-management'
    container_name: vaa-rabbitmq
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    networks:
      - VAA
    ports:
      - "5672:5672"

volumes:
  mongo_data:
  mongo_config:

networks:
  VAA:
    name: VAA